[workspace]
authors = ["John Peters <jgpeters3@wisc.edu>"]
channels = ["conda-forge", "bioconda", "pytorch"]
name = "chammi"
platforms = ["linux-64"]
version = "0.1.0"

[environments]
score = ["score"]
submit = ["submit"]
extract = ["extract"]

[feature.extract.tasks.extract]
cmd = "python scripts/distributed_eval.py"

[feature.score.tasks.score]
cmd = "python scripts/mass_scoring.py -l"

[feature.score.tasks.print]
cmd = "python scripts/generate_score_summaries.py -i /mnt/cephfs/mir/jcaicedo/projects/foundation_models_and_benchmarking/testing_scores"

[feature.extract.system-requirements]
cuda = "12.4"

[dependencies]
python = "3.11.*"
pytorch = ">=2.7.0,<3"
torchvision = ">=0.22.0,<0.23"
pandas = ">=2.3.0,<3"
pip = "*"
numpy = ">=1.20.0,<2"
pyzmq = ">=27.0.0, <28"
wandb = ">=0.20.1, <0.21"
polars = ">=1.31.0, <2"
eza = ">=0.23.0,<0.24"

[pypi-dependencies]
"CHAMMI" = { path = ".", editable = true }
lightning = ">=2.5.4, <3"
zarr = ">=3.1.2, <4"

[feature.score.dependencies]
faiss-gpu = "1.7.2.*"
matplotlib = ">=3.10.3,<4"
umap-learn = ">=0.5.7,<0.6"
seaborn = ">=0.13.2,<0.14"
wandb = ">=0.20.1,<0.21"

[feature.extract.dependencies]
cellpose = "3.0.11.*"
polars-lts-cpu = "1.22.0.*"
safetensors = "0.5.2.*"
scikit-image = "0.25.2.*"
scikit-learn = "1.6.1.*"
ipykernel = "*"
faiss-cpu = "*"
timm = ">=1.0.15,<2"
omegaconf = ">=2.3.0,<3"

[feature.extract.pypi-dependencies]
rich = ">=14.0.0, <15"

[feature.submit.pypi-dependencies]
argparse = ">=1.4.0, <2"
rich = ">=14.0.0, <15"

[feature.submit.dependencies]
snakemake = ">=9.6.2,<10"

