[workspace]
authors = ["John Peters <jgpeters3@wisc.edu>"]
channels = ["conda-forge", "bioconda", "pytorch"]
name = "chammi"
platforms = ["linux-64"]
version = "0.1.0"

[feature.extract.tasks.extract]
args = ["name"]
cmd = "python morphem/feature_extraction.py --root-dir /scr/data/CHAMMI/dataset/ --feat-dir /scr/jpeters/chammi_eval/{{ name }} --model dinov2 --model-size base --model-path /scr/jpeters/dino_artifacts/{{ name }} --gpu 0 --batch-size 256 --name {{ name }}" 

[feature.score.tasks.score]
args = ["name"]
cmd = "python morphem/benchmark.py --root-dir /scr/data/CHAMMI/dataset --dest-dir /scr/jpeters/CHAMMI_scores/{{ name }} --feature-dir /scr/jpeters/chammi_eval/{{ name }} --feature-file pretrained_dinov2_vit_features.npy" 
[environments]
score = ["score"]
extract = ["extract"]

[tasks.eval]
args = ["name"]
depends-on = [
  { task = "extract", environment = "extract", args=["{{ name }}"]},
  { task = "score", environment = "score", args=["{{ name }}"]},
]

[system-requirements]
cuda = "12.4"

[dependencies]
python = "3.11.*"
pytorch = ">=2.7.0,<3"
torchvision = ">=0.22.0,<0.23"
pandas = ">=2.3.0,<3"
pip = "*"
numpy = ">=1.20.0,<2"

[feature.score.dependencies]
faiss-gpu = "1.7.2.*"
matplotlib = ">=3.10.3,<4"
umap-learn = ">=0.5.7,<0.6"
seaborn = ">=0.13.2,<0.14"

[feature.extract.dependencies]
cellpose = "3.0.11.*"
polars-lts-cpu = "1.22.0.*"
safetensors = "0.5.2.*"
scikit-image = "0.25.2.*"
scikit-learn = "1.6.1.*"
ipykernel = "*"
faiss-cpu = "*"
timm = ">=1.0.15,<2"
omegaconf = ">=2.3.0,<3"
wandb = ">=0.20.1,<0.21"
