_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 12
feat_dir:
    value: /scr/jpeters/chammi_eval/vit_s_default_params
gpu:
    value: 0
model:
    value: dinov2
model_path:
    value: /scr/jpeters/dino_artifacts/vit_s_default_params
model_size:
    value: base
name:
    value: test_eval_dinov2
root_dir:
    value: /scr/data/CHAMMI/dataset/
